---
abstract: 'Unoffical notifo.com API'
author:
  - 'Andy Armstrong <andy@hexten.net>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Notifo
provides:
  WWW::Notifo:
    file: lib/WWW/Notifo.pm
    version: 0.01
requires:
  Getopt::Long: 0
  JSON: 2.00
  LWP::UserAgent: 0
  MIME::Base64: 0
  Test::Deep: 0
  Test::More: 0
  accessors::ro: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
